function Obj = SOFAgetConventions(sofaconventions,flags)
%SOFAGETVARIABLES
%   Obj = SOFAgetConventions(sofaconventions,flags) returns a list of variables and attributes.

% SOFA API - function SOFAgetConventions
% Copyright (C) 2012-2013 Acoustics Research Institute - Austrian Academy of Sciences
% Licensed under the EUPL, Version 1.1 or ñ as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence")
% You may not use this work except in compliance with the Licence.
% You may obtain a copy of the Licence at: http://joinup.ec.europa.eu/software/page/eupl
% Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the Licence for the specific language governing  permissions and limitations under the Licence. 

if ~exist('flags','var')
    flags='m'; % flags: m: mandatory, r: readonly
end

dims={'I';'R';'E';'N';'M';'C';'Q'}; % dimensions
flagc=cellstr((flags)');

switch sofaconventions
%% SimpleFreeFieldHRIR
    case 'SimpleFreeFieldHRIR'
        % name, value, flags, dimensions
        metadataarray={ ...
         'GLOBAL_Conventions' 'SOFA' 'rm'  ''; ...
         'GLOBAL_SOFAConventions' 'SimpleFreeFieldHRIR' 'rm'  ''; ...
         'GLOBAL_SOFAConventionVersion' '0.0.1' 'rm'  ''; ...
         'GLOBAL_APIName' 'Matlab ARI' 'rm'  ''; ...
         'GLOBAL_APIVersion' '0.0.1' 'rm'  ''; ...
         'GLOBAL_ApplicationName' '' 'm'  ''; ...
         'GLOBAL_ApplicationVersion' '' 'm'  ''; ...
         'GLOBAL_AuthorContact' 'sofaconventions' 'm'  ''; ...
         'GLOBAL_Licence' 'CC BY-SA 3.0' 'm'  ''; ...
         'GLOBAL_Organization' '' 'm'  ''; ...
         'GLOBAL_DatabaseName' '' 'm'  ''; ...
         'GLOBAL_SubjectID' '' 'm'  ''; ...
         'GLOBAL_RoomType' 'free field' 'm'  ''; ...
         'GLOBAL_DataType' 'FIR' 'm'  ''; ...
				 'GLOBAL_History' '' '' ''; ...
         'I' 1 'rm' ''; ...			% used for the sIngleton dimension
         'R' 2 'm'  ''; ...
         'E' 1 'm'  ''; ...
         'N' 1 'm'  ''; ...
         'M' 1 'm'  ''; ...
         'C' 3 'rm'  ''; ...
         'I_LongName' 'singleton dimension' 'rm' ''; ...
         'R_LongName' 'number of receivers' 'rm'  ''; ...
         'E_LongName' 'number of emitters' 'rm'  ''; ...
         'M_LongName' 'number of measurements' 'rm'  ''; ...
         'C_LongName' 'coordinate triplet' 'rm'  ''; ...
         'N_LongName' 'time' 'm'  ''; ...
         'N_Units' 'samples' 'm'  ''; ...
         'ListenerPosition' [1 0 0] 'm'  {'IC','MC'}; ...
         'ListenerPosition_Type' 'cartesian' 'm'  ''; ...
         'ListenerPosition_Units' 'meter' 'm'  ''; ...
         'ListenerUp' [1.2 0 1] 'm'  {'IC','MC'}; ...
         'ListenerUp_Type' 'cartesian' 'm'  ''; ...
         'ListenerUp_Units' 'meter' 'm'  ''; ...
         'ListenerView' [0 0 0] 'm'  {'IC','MC'}; ...
         'ListenerView_Type' 'cartesian' 'm'  ''; ...
         'ListenerView_Units' 'meter' 'm'  ''; ...
         'ListenerRotation' [0 0 0] 'm'  {'IC','MC'}; ...
         'ListenerRotation_Type' 'din9300' 'm'  ''; ...
         'ListenerRotation_Units' 'degrees' 'm'  ''; ...
         'ReceiverPosition' [0 -0.09 0; 0 0.09 0] 'm'  {'rC','rCM'}; ...
         'ReceiverPosition_Type' 'cartesian' 'm'  ''; ...
         'ReceiverPosition_Units' 'meter' 'm'  ''; ...
         'SourcePosition' [0 0 0] 'm'  {'IC','MC'}; ...
         'SourcePosition_Type' 'cartesian' 'm'  ''; ...
         'SourcePosition_Units' 'meter' 'm'  ''; ...
         'SourceUp' [0 0 1] 'm'  {'IC','MC'}; ...
         'SourceUp_Type' 'cartesian' 'm'  ''; ...
         'SourceUp_Units' 'meter' 'm'  ''; ...
         'SourceView' [1 0 0] 'm'  {'IC','MC'}; ...
         'SourceView_Type' 'cartesian' 'm'  ''; ...
         'SourceView_Units' 'meter' 'm'  ''; ...         
         'EmitterPosition' [0 0 0] 'm'  {'eC','eCM'}; ...
         'EmitterPosition_Type' 'cartesian' 'm'  ''; ...
         'EmitterPosition_Units' 'meter' 'm'  ''; ...         
        }; 
    dataarray={ ...
         'IR' [1 1] 'm'  'mRn'; ...
         'SamplingRate' 48000 'm'  'I'; ...
         'SamplingRate_Units' 'hertz' 'm'  ''; ...
     };
                 
%% SimpleDRIRMicArray   
  case 'SimpleDRIRMicArray'
		error('Not defined yet.');		
	otherwise 
		error(['This API does not support the conventions "' sofaconventions '".']);
end


%% create metadata structure
for ii=1:size(metadataarray,1)
	if  ~isempty(cell2mat(regexp(metadataarray{ii,3},flagc)))
		Obj.(metadataarray{ii,1})=metadataarray{ii,2};
		if isempty(strfind(metadataarray{ii,1},'_')) && ~sum(strcmp(metadataarray{ii,1},dims))
				Obj.Dimensions.(metadataarray{ii,1})=metadataarray{ii,4};
		end
	end
end

%% create data structure
for ii=1:size(dataarray,1)
    if ~isempty(cell2mat(regexp(dataarray{ii,3},flagc)))
        Obj.Data.(dataarray{ii,1})=dataarray{ii,2};
        if isempty(strfind(dataarray{ii,1},'_'))
            Obj.Dimensions.Data.(dataarray{ii,1})=dataarray{ii,4};
        end
    end
end