function vars = SOFAgetVariables(type)
%SOFAGETVARIABLES
%   vars = SOFAgetVariables(type) returns a list of variables.

% SOFA API - function SOFAsave
% Copyright (C) 2012 Acoustics Research Institute - Austrian Academy of Sciences
% Licensed under the EUPL, Version 1.1 or ñ as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence")
% You may not use this work except in compliance with the Licence.
% You may obtain a copy of the Licence at: http://www.osor.eu/eupl
% Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the Licence for the specific language governing  permissions and limitations under the Licence. 

%% ------------ list of mandatory variables and default values ------------
% first entry of cell is variable name
% second entry of cell is default value
% empty string -> mandatory variable
Mandatory = {...
  {'Data',''}, ...
  {'DataType','FIR'}, ...
  {'SourcePositionType',''}, ...
  {'SourceViewType',''}, ...
  {'SourceUpType',''}, ...
  {'TransmitterPositionType',''}, ...
  {'ListenerPositionType',''}, ...
  {'ListenerUpType',''}, ...
  {'ReceiverPositionType',''}, ...
  {'RoomType',''}, ...
  {'SamplingRate',''}, ...
  {'ListenerPosition',''}, ...
  {'ListenerView',''}, ...
  {'ListenerUp',''}, ...
  {'ListenerRotation',[0 0 0]}, ...
  {'ReceiverPosition',[0 0 0]}, ...
  {'SourcePosition',''}, ...
  {'SourceView',''}, ...
  {'SourceUp',''}, ...
  {'SourceRotation',[0 0 0]}, ...
  {'TransmitterPosition',[0 0 0]} ...
};

%% ------------------ list of source/listener variables -------------------
SourceListener = {'ListenerPosition', ...
    'ListenerView', ...
    'ListenerUp', ...
    'ListenerRotation', ...
	'SourcePosition', ...
    'SourceView', ...
    'SourceUp', ...
    'SourceRotation' ...
};

%% --------------- list of transmitter/receiver variables -----------------
TransmitterReceiver = {'ReceiverPosition', ...
    'TransmitterPosition' ...
};

%% ---------------------- return specified variables ----------------------
switch type
    case 'mandatory'
        vars=Mandatory;
    case 'sourcelistener'
        vars=SourceListener;
    case 'transmitterreceiver'
        vars=TransmitterReceiver;
    otherwise
        vars=[];
end

end %of function